### ISSUE TITLE
HU07: Crear un album

### ISSUE THREAD

**Issue by jhonavil2003** [jhonavil2003/MISW4203-202415-G17-APP-VINILOS#7]
Como colecionista quiero agregar un álbum a un listado.

**Criterios de Aceptación:**
- En el formulario se debe poder capturar los datos del nombre, la imagen de la carátula, la fecha de salida al mercado, una descripción, el género, la casa discográfica, el artista (o lista de artistas) y el listado de tracks.
- El campo de nombre no puede estar vacío y debe ser de tipo texto.
- El campo imagen de la caratula no puede estar vacío y debe tener la estructura de una url.
- El campo fecha de salida al mercado debe tener el formato de fecha DD/MM/YYYY
- El campo descripción debe ser de tipo texto y no exceder los 200 caracteres.
- El campo género se debe poder elegir una opción de una lista de selección.
- El campo Casa discográfica se debe poder elegir  de una lista de selección .
- Al hacer click en el botón crear  se deben validar los campos y si todo es correcto se debe crear el album.

**Tareas:**
- [ ]  Diseño de la interfaz
- [x]  Implementar consumo de servicio para crear album
- [x]  Pruebas Unitarias
- [x]  Pruebas funcionales
- [x] Despliegue

**Comment by jnarro-miso** [comment]
Jairo: 
- Diseño de la interfaz
- Implementar consumo de servicio para crear album

Zamir: 
- Pruebas Unitarias
- Pruebas funcionales
- Despliegue
